"""Text↔audio position sync — uses sync maps generated by TTS/STT."""

from __future__ import annotations

from typing import Any
from uuid import UUID

from brainycat.db import fetch_all, fetch_one


async def get_sync_map(book_id: str) -> list[dict[str, Any]]:
    """Get sync map for a book — chapter-level text↔audio mapping."""
    rows = await fetch_all("SELECT * FROM sync_maps WHERE book_id = $1 ORDER BY chapter_index", UUID(book_id))
    return [
        {
            "chapter_index": r["chapter_index"],
            "text_file_id": str(r["text_file_id"]),
            "audio_file_id": str(r["audio_file_id"]),
            "mappings": r["mappings"],
        }
        for r in rows
    ]


async def translate_position(book_id: str, from_type: str, position: str) -> dict[str, Any]:
    """Translate a text position to audio timestamp or vice versa."""
    maps = await fetch_all("SELECT * FROM sync_maps WHERE book_id = $1 ORDER BY chapter_index", UUID(book_id))
    if not maps:
        return {"error": "No sync map. Generate audio (TTS) or transcription (STT) first."}

    total_chapters = len(maps)

    if from_type == "text":
        # Position is a percentage (0-100) → find the corresponding chapter + offset
        try:
            pct = float(position)
        except ValueError:
            return {"error": "Position must be a number (percentage)"}

        chapter_idx = int(pct / 100 * total_chapters)
        chapter_idx = min(chapter_idx, total_chapters - 1)

        # Find the audio file for this chapter
        maps[chapter_idx]
        audio_files = await fetch_all(
            "SELECT id, file_name FROM book_files WHERE book_id = $1 AND format IN ('mp3','m4b','m4a') ORDER BY file_name",
            UUID(book_id),
        )
        if chapter_idx < len(audio_files):
            return {
                "chapter": chapter_idx,
                "audio_file_id": str(audio_files[chapter_idx]["id"]),
                "audio_file_name": audio_files[chapter_idx]["file_name"],
                "position_in_chapter": 0,
            }
        return {"chapter": chapter_idx, "error": "No matching audio file"}

    if from_type == "audio":
        # Position is chapter index → find text percentage
        try:
            chapter_idx = int(position)
        except ValueError:
            return {"error": "Position must be a chapter index"}

        pct = (chapter_idx / total_chapters) * 100 if total_chapters > 0 else 0
        return {"percentage": round(pct, 1), "chapter": chapter_idx}

    return {"error": f"Unknown from_type: {from_type}"}


async def has_sync(book_id: str) -> bool:
    """Check if a book has sync maps (TTS or STT was run)."""
    row = await fetch_one("SELECT 1 FROM sync_maps WHERE book_id = $1 LIMIT 1", UUID(book_id))
    return row is not None
